export const laboratory = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
`
export const laboratoryMedia = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
`
export const laboratoryProgramming = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
`
export const laboratoryEnginner = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi ipsum, eligendi voluptatum laborum distinctio laboriosam assumenda aspernatur facilis mollitia quos similique, porro cum esse unde quasi quaerat, laudantium amet soluta.
`